<?php

	return [
		['currency' => 'Afghani', 'code' => 'AFN'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Lek', 'code' => 'ALL'],
		['currency' => 'Algerian Dinar', 'code' => 'DZD'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Kwanza', 'code' => 'AOA'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'Argentine Peso', 'code' => 'ARS'],
		['currency' => 'Armenian Dram', 'code' => 'AMD'],
		['currency' => 'Aruban Florin', 'code' => 'AWG'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Azerbaijan Manat', 'code' => 'AZN'],
		['currency' => 'Bahamian Dollar', 'code' => 'BSD'],
		['currency' => 'Bahraini Dinar', 'code' => 'BHD'],
		['currency' => 'Taka', 'code' => 'BDT'],
		['currency' => 'Barbados Dollar', 'code' => 'BBD'],
		['currency' => 'Belarusian Ruble', 'code' => 'BYN'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Belize Dollar', 'code' => 'BZD'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Bermudian Dollar', 'code' => 'BMD'],
		['currency' => 'Indian Rupee', 'code' => 'INR'],
		['currency' => 'Ngultrum', 'code' => 'BTN'],
		['currency' => 'Boliviano', 'code' => 'BOB'],
		['currency' => 'Mvdol', 'code' => 'BOV'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Convertible Mark', 'code' => 'BAM'],
		['currency' => 'Pula', 'code' => 'BWP'],
		['currency' => 'Norwegian Krone', 'code' => 'NOK'],
		['currency' => 'Brazilian Real', 'code' => 'BRL'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Brunei Dollar', 'code' => 'BND'],
		['currency' => 'Bulgarian Lev', 'code' => 'BGN'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Burundi Franc', 'code' => 'BIF'],
		['currency' => 'Cabo Verde Escudo', 'code' => 'CVE'],
		['currency' => 'Riel', 'code' => 'KHR'],
		['currency' => 'CFA Franc BEAC', 'code' => 'XAF'],
		['currency' => 'Canadian Dollar', 'code' => 'CAD'],
		['currency' => 'Cayman Islands Dollar', 'code' => 'KYD'],
		['currency' => 'CFA Franc BEAC', 'code' => 'XAF'],
		['currency' => 'CFA Franc BEAC', 'code' => 'XAF'],
		['currency' => 'Chilean Peso', 'code' => 'CLP'],
		['currency' => 'Unidad de Fomento', 'code' => 'CLF'],
		['currency' => 'Yuan Renminbi', 'code' => 'CNY'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'Colombian Peso', 'code' => 'COP'],
		['currency' => 'Unidad de Valor Real', 'code' => 'COU'],
		['currency' => 'Comorian Franc', 'code' => 'KMF'],
		['currency' => 'Congolese Franc', 'code' => 'CDF'],
		['currency' => 'CFA Franc BEAC', 'code' => 'XAF'],
		['currency' => 'New Zealand Dollar', 'code' => 'NZD'],
		['currency' => 'Costa Rican Colon', 'code' => 'CRC'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Kuna', 'code' => 'HRK'],
		['currency' => 'Cuban Peso', 'code' => 'CUP'],
		['currency' => 'Peso Convertible', 'code' => 'CUC'],
		['currency' => 'Netherlands Antillean Guilder', 'code' => 'ANG'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Czech Koruna', 'code' => 'CZK'],
		['currency' => 'Danish Krone', 'code' => 'DKK'],
		['currency' => 'Djibouti Franc', 'code' => 'DJF'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'Dominican Peso', 'code' => 'DOP'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Egyptian Pound', 'code' => 'EGP'],
		['currency' => 'El Salvador Colon', 'code' => 'SVC'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'CFA Franc BEAC', 'code' => 'XAF'],
		['currency' => 'Nakfa', 'code' => 'ERN'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Lilangeni', 'code' => 'SZL'],
		['currency' => 'Ethiopian Birr', 'code' => 'ETB'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Falkland Islands Pound', 'code' => 'FKP'],
		['currency' => 'Danish Krone', 'code' => 'DKK'],
		['currency' => 'Fiji Dollar', 'code' => 'FJD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'CFP Franc', 'code' => 'XPF'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'CFA Franc BEAC', 'code' => 'XAF'],
		['currency' => 'Dalasi', 'code' => 'GMD'],
		['currency' => 'Lari', 'code' => 'GEL'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Ghana Cedi', 'code' => 'GHS'],
		['currency' => 'Gibraltar Pound', 'code' => 'GIP'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Danish Krone', 'code' => 'DKK'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Quetzal', 'code' => 'GTQ'],
		['currency' => 'Pound Sterling', 'code' => 'GBP'],
		['currency' => 'Guinean Franc', 'code' => 'GNF'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Guyana Dollar', 'code' => 'GYD'],
		['currency' => 'Gourde', 'code' => 'HTG'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Lempira', 'code' => 'HNL'],
		['currency' => 'Hong Kong Dollar', 'code' => 'HKD'],
		['currency' => 'Forint', 'code' => 'HUF'],
		['currency' => 'Iceland Krona', 'code' => 'ISK'],
		['currency' => 'Indian Rupee', 'code' => 'INR'],
		['currency' => 'Rupiah', 'code' => 'IDR'],
		['currency' => 'SDR (Special Drawing Right)', 'code' => 'XDR'],
		['currency' => 'Iranian Rial', 'code' => 'IRR'],
		['currency' => 'Iraqi Dinar', 'code' => 'IQD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Pound Sterling', 'code' => 'GBP'],
		['currency' => 'New Israeli Sheqel', 'code' => 'ILS'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Jamaican Dollar', 'code' => 'JMD'],
		['currency' => 'Yen', 'code' => 'JPY'],
		['currency' => 'Pound Sterling', 'code' => 'GBP'],
		['currency' => 'Jordanian Dinar', 'code' => 'JOD'],
		['currency' => 'Tenge', 'code' => 'KZT'],
		['currency' => 'Kenyan Shilling', 'code' => 'KES'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'North Korean Won', 'code' => 'KPW'],
		['currency' => 'Won', 'code' => 'KRW'],
		['currency' => 'Kuwaiti Dinar', 'code' => 'KWD'],
		['currency' => 'Som', 'code' => 'KGS'],
		['currency' => 'Lao Kip', 'code' => 'LAK'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Lebanese Pound', 'code' => 'LBP'],
		['currency' => 'Loti', 'code' => 'LSL'],
		['currency' => 'Rand', 'code' => 'ZAR'],
		['currency' => 'Liberian Dollar', 'code' => 'LRD'],
		['currency' => 'Libyan Dinar', 'code' => 'LYD'],
		['currency' => 'Swiss Franc', 'code' => 'CHF'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Pataca', 'code' => 'MOP'],
		['currency' => 'Denar', 'code' => 'MKD'],
		['currency' => 'Malagasy Ariary', 'code' => 'MGA'],
		['currency' => 'Malawi Kwacha', 'code' => 'MWK'],
		['currency' => 'Malaysian Ringgit', 'code' => 'MYR'],
		['currency' => 'Rufiyaa', 'code' => 'MVR'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Ouguiya', 'code' => 'MRU'],
		['currency' => 'Mauritius Rupee', 'code' => 'MUR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'ADB Unit of Account', 'code' => 'XUA'],
		['currency' => 'Mexican Peso', 'code' => 'MXN'],
		['currency' => 'Mexican Unidad de Inversion (UDI)', 'code' => 'MXV'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Moldovan Leu', 'code' => 'MDL'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Tugrik', 'code' => 'MNT'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'Moroccan Dirham', 'code' => 'MAD'],
		['currency' => 'Mozambique Metical', 'code' => 'MZN'],
		['currency' => 'Kyat', 'code' => 'MMK'],
		['currency' => 'Namibia Dollar', 'code' => 'NAD'],
		['currency' => 'Rand', 'code' => 'ZAR'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'Nepalese Rupee', 'code' => 'NPR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'CFP Franc', 'code' => 'XPF'],
		['currency' => 'New Zealand Dollar', 'code' => 'NZD'],
		['currency' => 'Cordoba Oro', 'code' => 'NIO'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Naira', 'code' => 'NGN'],
		['currency' => 'New Zealand Dollar', 'code' => 'NZD'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Norwegian Krone', 'code' => 'NOK'],
		['currency' => 'Rial Omani', 'code' => 'OMR'],
		['currency' => 'Pakistan Rupee', 'code' => 'PKR'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Balboa', 'code' => 'PAB'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Kina', 'code' => 'PGK'],
		['currency' => 'Guarani', 'code' => 'PYG'],
		['currency' => 'Sol', 'code' => 'PEN'],
		['currency' => 'Philippine Peso', 'code' => 'PHP'],
		['currency' => 'New Zealand Dollar', 'code' => 'NZD'],
		['currency' => 'Zloty', 'code' => 'PLN'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Qatari Rial', 'code' => 'QAR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Romanian Leu', 'code' => 'RON'],
		['currency' => 'Russian Ruble', 'code' => 'RUB'],
		['currency' => 'Rwanda Franc', 'code' => 'RWF'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Saint Helena Pound', 'code' => 'SHP'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'East Caribbean Dollar', 'code' => 'XCD'],
		['currency' => 'Tala', 'code' => 'WST'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Dobra', 'code' => 'STN'],
		['currency' => 'Saudi Riyal', 'code' => 'SAR'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'Serbian Dinar', 'code' => 'RSD'],
		['currency' => 'Seychelles Rupee', 'code' => 'SCR'],
		['currency' => 'Leone', 'code' => 'SLL'],
		['currency' => 'Singapore Dollar', 'code' => 'SGD'],
		['currency' => 'Netherlands Antillean Guilder', 'code' => 'ANG'],
		['currency' => 'Sucre', 'code' => 'XSU'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Solomon Islands Dollar', 'code' => 'SBD'],
		['currency' => 'Somali Shilling', 'code' => 'SOS'],
		['currency' => 'Rand', 'code' => 'ZAR'],
		['currency' => 'South Sudanese Pound', 'code' => 'SSP'],
		['currency' => 'Euro', 'code' => 'EUR'],
		['currency' => 'Sri Lanka Rupee', 'code' => 'LKR'],
		['currency' => 'Sudanese Pound', 'code' => 'SDG'],
		['currency' => 'Surinam Dollar', 'code' => 'SRD'],
		['currency' => 'Norwegian Krone', 'code' => 'NOK'],
		['currency' => 'Swedish Krona', 'code' => 'SEK'],
		['currency' => 'Swiss Franc', 'code' => 'CHF'],
		['currency' => 'WIR Euro', 'code' => 'CHE'],
		['currency' => 'WIR Franc', 'code' => 'CHW'],
		['currency' => 'Syrian Pound', 'code' => 'SYP'],
		['currency' => 'New Taiwan Dollar', 'code' => 'TWD'],
		['currency' => 'Somoni', 'code' => 'TJS'],
		['currency' => 'Tanzanian Shilling', 'code' => 'TZS'],
		['currency' => 'Baht', 'code' => 'THB'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'CFA Franc BCEAO', 'code' => 'XOF'],
		['currency' => 'New Zealand Dollar', 'code' => 'NZD'],
		['currency' => 'Pa\'anga', 'code' => 'TOP'],
		['currency' => 'Trinidad and Tobago Dollar', 'code' => 'TTD'],
		['currency' => 'Tunisian Dinar', 'code' => 'TND'],
		['currency' => 'Turkish Lira', 'code' => 'TRY'],
		['currency' => 'Turkmenistan New Manat', 'code' => 'TMT'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'Australian Dollar', 'code' => 'AUD'],
		['currency' => 'Uganda Shilling', 'code' => 'UGX'],
		['currency' => 'Hryvnia', 'code' => 'UAH'],
		['currency' => 'UAE Dirham', 'code' => 'AED'],
		['currency' => 'Pound Sterling', 'code' => 'GBP'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'US Dollar (Next day)', 'code' => 'USN'],
		['currency' => 'Peso Uruguayo', 'code' => 'UYU'],
		['currency' => 'Uruguay Peso en Unidades Indexadas (UI)', 'code' => 'UYI'],
		['currency' => 'Unidad Previsional', 'code' => 'UYW'],
		['currency' => 'Uzbekistan Sum', 'code' => 'UZS'],
		['currency' => 'Vatu', 'code' => 'VUV'],
		['currency' => 'Bolívar Soberano', 'code' => 'VES'],
		['currency' => 'Dong', 'code' => 'VND'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'US Dollar', 'code' => 'USD'],
		['currency' => 'CFP Franc', 'code' => 'XPF'],
		['currency' => 'Moroccan Dirham', 'code' => 'MAD'],
		['currency' => 'Yemeni Rial', 'code' => 'YER'],
		['currency' => 'Zambian Kwacha', 'code' => 'ZMW'],
		['currency' => 'Zimbabwe Dollar', 'code' => 'ZWL']
	];