[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
startretries=10
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log

[program:laravel-scheduler]
process_name=%(program_name)s
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
startretries=10
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/scheduler.log


# [program:laravel-worker]
# process_name=%(program_name)s_%(process_num)02d
# command=php /var/www/html/artisan queue:work --sleep=3 --tries=3
# autostart=true
# autorestart=true
# startsecs=0
# startretries=999
# user=www-data
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/var/www/html/storage/logs/worker.log